services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: lms-frontend
    restart: unless-stopped
    networks:
      - traefik_public
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.lms-frontend.rule=Host(`sqwoz-hrov.ru`) && PathPrefix(`/lms`)'
      - 'traefik.http.routers.lms-frontend.entrypoints=websecure'
      - 'traefik.http.routers.lms-frontend.tls=true'
      - 'traefik.http.routers.lms-frontend.tls.certresolver=myresolver'
      - 'traefik.http.routers.lms-frontend.service=lms-frontend'
      - 'traefik.http.services.lms-frontend.loadbalancer.server.port=80'
      - 'traefik.http.routers.lms-frontend.middlewares=lms-frontend-stripprefix@docker'
      - 'traefik.http.middlewares.lms-frontend-stripprefix.stripprefix.prefixes=/lms'
      - 'traefik.docker.network=traefik_public'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env

networks:
  traefik_public:
    external: true
