services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.stage
    container_name: lms-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DEV_PORT=${DEV_PORT:-5173}
      - HMR_PROTOCOL=wss
      - HMR_HOST=stage.sqwoz-hrov.ru
      - HMR_CLIENT_PORT=${DEV_HMR_CLIENT_PORT:-443}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - traefik_public
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.lms-frontend.rule=Host(`stage.sqwoz-hrov.ru`) && PathPrefix(`/lms`)'
      - 'traefik.http.routers.lms-frontend.entrypoints=websecure'
      - 'traefik.http.routers.lms-frontend.tls=true'
      - 'traefik.http.routers.lms-frontend.tls.certresolver=myresolver'
      - 'traefik.http.routers.lms-frontend.service=lms-frontend'
      - 'traefik.http.services.lms-frontend.loadbalancer.server.port=${DEV_PORT:-5173}'
      - 'traefik.docker.network=traefik_public'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    
networks:
  traefik_public:
    external: true
